# Generated by Django 3.2.4 on 2021-06-21 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('active', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'NOT_ACTIVE'), (3, 'ACCEPTED')], verbose_name='Статус')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59))),
                ('receiver_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_subs', to='oper.subscriber', verbose_name='Получатель')),
                ('sender_subs_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oper.subscriber', verbose_name='Отправитель')),
            ],
        ),
    ]
